version: '2'
services:
  mqtt_db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
    - "5432:5432"
    container_name: "postgres-mosq"
    networks:
    - mosqnet

  mosquitto:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-mosquitto
    container_name: "broker-mosq"
    volumes:
    - ${PWD}/mqtt.conf:/etc/mosquitto/mosquitto.conf 
    ports:
    - "1883:1883"
    - "1884:1884"
    networks:
    - mosqnet
    depends_on:
    - mqtt_db
    labels:
    - "local.example.description=Mosquitto v1.4.10 MQTT server"
    command: ["./wait-for-postgres.sh", "mqtt_db", "mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]

networks:
  mosqnet:

